### ISSUE TITLE
`ip` field in login requests

### ISSUE THREAD

**Issue by hyperdefined** [ToontownRewritten/api-doc#17]
Within this the last week, there was an `ip` field added to a successful login request. This ended up breaking my [custom launcher](https://github.com/hyperdefined/CustomLauncherRewrite), and was wondering what this was going to be used for.

```
{cookie=xxx, success=true, manifest=/content/patchmanifest.txt, gameserver=gameserver.toontownrewritten.com:31363, ip=null}
```

**Comment by Hawkheart** [comment]
Hello,

This was to be used for a feature we're experimenting with. We've decided that it won't be needed in the end, so it's been removed again. Apologies for (temporarily) breaking API contract!
